    obtencionClima.cron = 0 0/5 * * * *
alerta.cron = 0 * * * * *

# Lista de destinatarios separados por coma
# alert.recipients=admin@clima.com,emergencias@clima.com,meteorologia@clima.com

alert.recipients=miranda.martin.2004@gmail.com

# Umbral máximo de temperatura
alert.tempMax=1

# Umbral máximo de humedad
alert.humMax=1

weather.api.base = http://api.weatherapi.com/v1
weather.api.key= ${weather.key}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${mi.email}
spring.mail.password=${mail.password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.config.import=optional:application-local.properties